sudo: required
language: generic
services:
   - docker

before_install:
   - docker build -t zambago/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true zambago/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   name: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-us-east-2-333536548221"
   bucket_path: "docker-react"
     on:
       branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY 
