sudo: required
language: generic
services:
   - docker

before_install:
   - docker build -t zambago/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true zambago/docker-react npm run test -- --coverage
